language: node_js
node_js:
  - "8.9.1"
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - rm .gitignore
  - cp -r lib/* . && rm -fr lib
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
